version: '3.9'

services:
  app:
    build: .
    restart: always
    working_dir: /app
    volumes:
      - ./:/app:delegated
    ports:
      - 3000:3000
    command: "sh -c 'npm install && npm run start:debug'"
