apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 作成する全てのObjectに "env: development" というlabelを付与します
labels:
  - includeSelectors: true
    pairs:
      env: development

# developmentのnamespace内にObjectを配置します。
namespace: development

# MEMO: 重要な点です。
# 使用するマニフェストファイルを選択します。ここでbaseディレクトリのテンプレートを元に、同一ディレクトリのnamespace.yamlを統合したものを1つのマニフェストにまとめます。
resources:
  - ../../base
  - namespace.yaml

# resourcesで作成されたマニフェストに変更を加えます。
# 今回はPodを3から1つに変更するために使用します。
patches:
  - path: deployment.yaml
    target:
      kind: Deployment

# 指定したイメージnameのuriを書き換えます。
# 今回は1.25から1.24に変更します。
images:
  - name: nginx
    newName: nginx
    newTag: "1.24"
