apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-with-datadog
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/container-dependencies: '{"app":["datadog"]}'
        run.googleapis.com/cpu-throttling: "false"

    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/learn-387812/learn/hello-py
          name: app
          env:
            - name: DD_SERVICE
              value: hello
            - name: DD_ENV
              value: dev
          ports:
            - containerPort: 5050

        - image: datadog/agent:7
          name: datadog
          env:
            - name: DD_SITE
              value: ap1.datadoghq.com
            - name: DD_APM_ENABLED
              value: "true"
            - name: DD_HOSTNAME
              value: cloudrun
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dd-api-key
                  key: latest
